### ISSUE TITLE
URL not correctly substituted

### ISSUE THREAD

**Issue by rozza-m** [circa10a/cv-notifier#2]
`2023-08-17 11:22:58.580 | INFO     | lib.webhooks.requests:process:74 - Object bear detected with confidence of 0.53. Notifying http://192.168.1.150:1880/yolo?person=0.53`

Note "bear" is detected but "person" is sent in the URL.

`2023-08-17 15:25:08.675 | INFO     | lib.webhooks.requests:process:74 - Object person detected with confidence of 0.84. Notifying http://192.168.1.150:1880/yolo?person=0.54`

Note confidence is wrong.

Config:
```
config:
  source: '[redacted]'
  webhooks:
    - url: http://[redacted]/yolo?$object_name=$object_confidence
      notifyInterval: 1900
      objects:
        - person
        - bear
        - horse
        - sheep
        - cow 
        - bird
        - cat
        - dog
      method: 'GET'
      headers:
        Content-Type: application/json
      body: >
        {
          "someKey": "$object_name detected with confidence score of $object_confidence"
        }
```
